### ISSUE TITLE
Armazenamento de dados

### ISSUE THREAD

**Issue by ftonato** [socialpullrequest/ongbd#1]
Opa @jonatasemidio, beleza?

Fiquei com dúvida, onde vamos armazenar a lista de ONGs, será um arquivo json, ou um banco de dados relacional, ou banco de dados orientado a W (Whatever)?

Gostaria de saber mais sobre isso para poder contribuir também...

**Comment by jonatasemidio** [comment]
Cara...  Que bom mais alguém por perto.

O Amorim usou a API do docs para chamar do jekyll para o spreadsheet... De
início seria armazenado no drive mesmo...  Mas como não sei proceguir com
isso acho q vou mudar para firebase

**Comment by ftonato** [comment]
Beleza @jonatasemidio, assim que mudar me avise e vamos tocando isso...

*Nota*: Percebi que não tô com permissões de fazer merge nos repositórios, tá normal isso? (Apago essa questão assim que me avisar sobre)

**Comment by jonatasemidio** [comment]
Opa...  Vou dar uma olhada.
